### ISSUE TITLE
Sometimes it's Impossible to predict the correct Belief state

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#16]
At  **simmc2_dials_dstc10_devtest_target.txt**, the following line exits:

> User : I'm interested in a hoodie. System : How do you feel about this brown one here on the front floor rack, and the brown one in front of it? They are both hoodies. <SOM> 47, 50 <EOM> User : What's the prive of the item? => Belief State : ASK:GET [  ] (price) < 36 > <EOB> Which item do you mean? <EOS>

But I think it's impossible to correctly predict the `object` at Belief State which is 36, when the model is given only the part before Belief State, because the user utterance contains ambiguity in it (so the system actually disambiguates it!).

If I'm right, this is a problem. Please let me know.

**Comment by heyzude** [comment]
In the description paper it says,

> Note that we exclude from evaluation the object mentions that are immediately followed by a disambiguation request

**Comment by shanemoon** [comment]
Hi @heyzude, thank you for your question.

It is true that there will be a soft upper-bound on the belief state prediction task, because some of the user utterances will inherently contain ambiguity. Since 10% of the turns are disambiguation turns, we expect ~90% being the soft upper bound performance. 

**Rationale:** 
We decided that a reference-resolving model should try to identify object mentions as best as they can do, regardless of whether there is an ambiguity in an utterance. Instead, we introduce a "disambiguation model", which makes a binary prediction of ambiguity presence in an utterance. We thought that this new task setup can isolate these two challenging problems, and potentially reduce complexity of each module. Note that we made this change in the evaluation setup after the arXiv publication (hence the confusion) -- we will clarify this in the challenge READMEs.
