### ISSUE TITLE
Data mentioned_object_ids

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#18]
![image](https://user-images.githubusercontent.com/48037590/127247710-ee6f0b0c-4a12-4f63-8449-5366fdbd8ae6.png)

In the picture, what is the difference between the **mentioned object ids in the red box** and the **mentioned object ids in the blue box**? My guess is that the red box refers to the "object" key in system_transcript_annotated and the blue box is the "mentioned_object_ids" key corresponding to the scene, right?

For example, when matching objects related to utterances in subtask2 inference, can we not use the mentioned object IDs corresponding to scenes? The below table describing subtaks2 introduces input of "urrent user utterance with objection mentions". I am confused. If the mentioned object IDs are not available, will all objects in the scene be candidates for matching?
![image](https://user-images.githubusercontent.com/48037590/127275447-5987c32e-7acb-4c94-9ae3-4503987552a6.png)

Thanks.

**Comment by shanemoon** [comment]
Hi @rungjoo, thank you for your question.

* `mentioned_object_ids` in the **blue** box lists all of the object IDs that are mentioned in each dialog by Assistant or User (where object ID is defined locally for each scene). Having access to the dialog-level `mentioned_object_ids` would essentially mean that at any given turn a model can "peak into future turns" and can technically use future information as part of modeling. This obviously can't be the case in real-world scenarios, which is why we are not making it visible at inference time. Sorry that this caused confusion -- we will clarify the language in the README doc. 

* `<int> objects` from `system_transcript_annotated` for each turn refers to the set of objects mentioned that in that particular turn, where object ID is defined locally for each scene as well.

* "Current user utterance with object mentions" should actually read "Current user utterance", because we are defining sub-task #2 for every turn, regardless of whether a turn includes an object mention. In case where there is no mention of an object, the model for Sub-task #2 should output an empty list `[]`.  Thank you for spotting this -- we will correct it in the README doc.

For Sub-task #2 -- please note that for any given turn, an object reference can either be from any of the objects in the scene (hence all of the objects in a scene technically being the candidates), or from objects that were mentioned in the past turns of the dialog. Hope this clarifies!
