### ISSUE TITLE
Is "color" allowed at inference time?

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#19]
![image](https://user-images.githubusercontent.com/12981081/127252834-e19d8e0a-e7bf-44df-9db7-f0e8c0d56dd7.png)

We can see that color belongs to both Non-visual Metadata and Visual Metadata at TASK_INPUTS.md, which brings confusion.

I think color should be allowed data, because detected color at the VR scene and color written at the json file don't match each other frequently.

**Comment by shanemoon** [comment]
Hi @heyzude, thank you for catching this error -- yes `color` should be part of visual metadata. The fix for the typo was made [here](https://github.com/facebookresearch/simmc2/commit/157dc0f661f3d8604f21a5935d33d0028ff9032b). 

We are excluding the textual color metadata as part of the allowed input for inference in order to advocate & encourage participants to leverage better CV models. A model that does e.g. coreference resolution simply based on textual similarities with the visual metadata (which is not always accurate anyways, as you mentioned) may not need to use the provided images at all, which would not be considered ideal for our SIMMC2 challenge. 

Thank you for your question!
