### ISSUE TITLE
Is multimodal disambiguation an official task?

### ISSUE THREAD

**Issue by bambidz** [facebookresearch/simmc2#21]
On the DSTC track 3 proposal, there was no disambiguation task. 
However in the paper and the TASK_INPUT.md the task exists, so I'm confused.

Is the multimodal disambiguation task also included in the competition?

**Comment by shanemoon** [comment]
Hi @bambidz, thank you for your question. Yes, Multimodal Disambiguation is an official task of SIMMC2. There has been increasing interest in the disambiguation handling systems in the dialog community, which is why we decided to include it as part of the challenge.

Please note that we do plan on announcing winner(s) for each of the four sub-tasks. Teams who submit results for a subset of the tasks will still be evaluated to be considered as sub-task winner(s) for the respective tasks they participated in.
