### ISSUE TITLE
Wrong evaluation for availableSizes.

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#41]
Hi, and thanks for your hard work organizing this track.

I'd like to question the way `availableSizes` of dst slot is evaluated. 
If the order of sizes at the list is changed, it is considered as wrong.

Thank you.

**Comment by shanemoon** [comment]
Hi @heyzude, thank you for raising this issue.

We agree that the order of the values is not important enough to distinguish for our task -- hence we just made a [commit](https://github.com/facebookresearch/simmc2/commit/741e6d32dc354b7c17de7a1b5ec639343f4286d6) that includes the modification such that the list of availableSizes is sorted first (so it sees a consistent ordering). 

Since this is a last minute change in the evaluation script, we also decided to postpone the code submission deadline a bit, in case participants need to make any adjustment. We will make an announcement soon - thank you!
