### ISSUE TITLE
Questions about the testutd retrieval candidate file containing only one turn

### ISSUE THREAD

**Issue by boychaboy** [facebookresearch/simmc2#45]
Hi, you have released the `simmc2_dials_dstc10_teststd_retrieval_candidates_public.json` data for the challenge phase 2. But I found out that the original the teststd data contains only one turn of candidates in each dialog. Since the original `simmc2_dials_dstc10_devtest_retrieval_candidates.json` file had candidates of multiple turns in a dialog, I just wanted to make sure that this modification was made on purpose. Thank you!

**Comment by satwikkottur** [comment]
Hello @boychaboy ,

Thanks for your interest!

This is indeed on purpose as both retrieval/generation on `teststd` is evaluated only for the last round present in the dialog file. Feel free to re-open this issue if you have more questions.

**Comment by shanemoon** [comment]
@boychaboy Just adding a bit more explanation -- because the ground-truth system responses for turns `1` through `K-1` are already in the released file (e.g. to be used for other subtasks), we decided to exclude them from the official evaluation. You can see more information on the evaluation criteria [here](https://github.com/facebookresearch/simmc2/blob/master/SUBMISSION_INSTRUCTIONS.md). Thank you!

**Comment by boychaboy** [comment]
@shanemoon @satwikkottur I totally got it! Thanks for your explanation:)
Then is it okay if I submit `subtask4-generation`: response for every turns for all dialogues,
and `subtask4-retrieval` : candidate scores for only the last turn of the dialogues?
Ofcourse, in format provided [here](https://github.com/facebookresearch/simmc2/blob/master/SUBMISSION_INSTRUCTIONS.md)
