### ISSUE TITLE
About GPT2 and MTN's performance at response generation

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#48]
Hi, and thank you for aggregating the results!

I have a question about the GPT2 and MTN's performace at response generation on teststd split.
I know GPT2 and MTN are great models, but as far as I know it's a bit hard to reach BLEU-4 score of 0.445 and 0.359, as GPT2 and MTN's performance on devtest is 0.192, 0.217 respectively.

So I wonder the evaluation was conducted correctly.
Sorry if my opinion is wrong.

**Comment by satwikkottur** [comment]
Hello @heyzude ,

Thanks a ton for participating in the challenge.

Your intuition is right! On re-investigating, we did an issue in the evaluation for the baseline models for assistant response generation, which overstated their performance. We updated the table in the SIMMC 2.0 official table [here][simmc_results].

The changes are as follows:
```
BLEU score for assistance response generation (4-2):
GPT-2: 0.445 -> 0.202
MTN: 0.359 -> 0.211
```

Apologies for any inconvenience caused due to this error. Please feel free to re-open the issue if you have further questions.

[simmc_results]:https://github.com/facebookresearch/simmc2/blob/main/CHALLENGE_RESULTS.md
